"""empty message

Revision ID: 45cae1bd3da2
Revises: dcfc78d3b3da
Create Date: 2018-11-10 22:05:58.391065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cae1bd3da2'
down_revision = 'dcfc78d3b3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('btc_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('cell_number', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('fiat_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gold_status', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'street')
    op.drop_column('users', 'state')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'gold_status')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'fiat_balance')
    op.drop_column('users', 'email')
    op.drop_column('users', 'city')
    op.drop_column('users', 'cell_number')
    op.drop_column('users', 'btc_balance')
    # ### end Alembic commands ###
