"""empty message

Revision ID: 5d86bc273788
Revises: 45cae1bd3da2
Create Date: 2018-11-13 19:03:23.412902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d86bc273788'
down_revision = '45cae1bd3da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog',
    sa.Column('lid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('xid', sa.Integer(), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('traderId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('lid')
    )
    op.create_table('orders',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('isBuy', sa.Boolean(), nullable=True),
    sa.Column('btc_amount', sa.Float(), nullable=True),
    sa.Column('xchange', sa.Float(), nullable=True),
    sa.Column('comm_type', sa.String(length=255), nullable=True),
    sa.Column('comm_amount', sa.Float(), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('traderId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('payments',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('fiatAmount', sa.Float(), nullable=True),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('traderId', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traderId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('changelog')
    # ### end Alembic commands ###
