"""empty message

Revision ID: 70adf3048b2d
Revises: e9ab027a3433
Create Date: 2018-11-10 19:53:12.843286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70adf3048b2d'
down_revision = 'e9ab027a3433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_manager')
    # ### end Alembic commands ###
