"""empty message

Revision ID: 80df60e6945d
Revises: 5d86bc273788
Create Date: 2018-11-13 19:10:06.562901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80df60e6945d'
down_revision = '5d86bc273788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changelog', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('changelog', 'xid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('orders', 'btc_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'comm_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('orders', 'comm_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'isBuy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('payments', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'isBuy',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('orders', 'comm_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'comm_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('orders', 'btc_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('changelog', 'xid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('changelog', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
