"""empty message

Revision ID: f7fad4e3313d
Revises: 27a7f777c09c
Create Date: 2018-11-16 11:06:54.588086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fad4e3313d'
down_revision = '27a7f777c09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('changelog', sa.Column('status', sa.String(length=255), nullable=False))
    op.add_column('changelog', sa.Column('xid_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('changelog', 'xid_type')
    op.drop_column('changelog', 'status')
    # ### end Alembic commands ###
